install:
  - set PATH=C:\Ruby27\bin;%PATH%
  - gem uninstall bundler --executables
  - gem install bundler -v '2.0.1'
  - bundle install

build: off

test_script:
  # Tests use real git commands
  - git config --global user.email "danger@example.com"
  - git config --global user.name "Danger McShane"
  - bundle exec rake specs
